### ISSUE TITLE
Unknown error in error.log

### ISSUE THREAD

**Issue by dimavisser** [Dropinbase/Releases#12]
Please remove this error or give it a lower priority - it had been spamming error.log file for months now for no apparent reason.

`
{
	"code" : 808,
	"date" : "2020-06-11 10:06:14",
	"user" : "12930741 (x3x4x5x6x14x)",
	"ip" : "::1",
	"dib_db_host" : "databasewisl_dev_dib(1) on 129.232.168.242",
	"url" : "https:\/\/dev.wisl.nwu.ac.za:443\/dropins\/setNgxMaterial\/plain\/Template\/controller\/placementOverview.js",
	"args" : {"[<required> $containerName]":"placementOverview","[<optional> $REQUEST_TYPE = 'GET,ignoretoken']":"GET"},
	"error" : 
Please ensure to run -> from the /vendor/dropinbase/dropinbase/dropins/setNgMaterial/angular/ folder; npm run watch:modules,
	"detail" : {

	},
	"trace" : [
		"TmplController.php(437):    Log::err(\"Please ensure to run -> from the \/vendor\/dropinbase\/dropinbase\/dropins\/setNgMaterial\/angular\/ folder... \")",
		"TemplateController.php(17):    TmplController->combineAll(\"placementOverview\", ARRAY, \"placementOverview_cxx3x4x5x6x14xx\", NULL, \"ng-ts\", \"ts\")",
		"TemplateController->controller(\"placementOverview\", \"GET\")",
		"ControllerFactory.php(157):    ReflectionMethod->invokeArgs(OBJECT, ARRAY)",
		"PeffApp.php(685):    ControllerFactory::run(\"controller\", ARRAY, ARRAY, ARRAY, \"setNgxMaterial\/plain\")",
		"PeffApp.php(340):    DibApp->createController()",
		"index.php(32):    DibApp->run()",
		"index.php(6):    include_once(\"C:\\CODE\\vendor\\dropinbase\\dropinbase\\index.php\")"
	]
}

----`

**Comment by cobuscoetsee** [comment]
Error log redone.
