### ISSUE TITLE
Can't change any properties in dibDesigner

### ISSUE THREAD

**Issue by dimavisser** [Dropinbase/Releases#16]
All I get is [object Object] toast and the values revert to where they were.

![image](https://user-images.githubusercontent.com/33894592/85278502-5355bf80-b485-11ea-92be-af34f57b7761.png)

**Comment by dimavisser** [comment]
Not just the value marked - ANY value in designer is now read only - I have to edit SQL directly.

**Comment by dimavisser** [comment]
Received from David Blake:

![image](https://user-images.githubusercontent.com/33894592/85284463-89983c80-b48f-11ea-9535-f9c4710b7442.png)

**Comment by dawie-git** [comment]
Issue fixed and closed
