### ISSUE TITLE
Clearing cache does not remove cached action/component files

### ISSUE THREAD

**Issue by dimavisser** [Dropinbase/Releases#20]
When selecting clear cache for a single container option (top right), the cache for custom TS events/actions on the items of that container does not get cleared. Also any custom components with cached TS files on that container do not reset their cache. 

So at the moment I either have to go to the /cache folder to manually remove the items or to use the red button - both these solutions result in time loss.

![image](https://user-images.githubusercontent.com/33894592/85434437-5b495880-b586-11ea-858c-34547661a206.png)

**Comment by cobuscoetsee** [comment]
Resolved.
