### ISSUE TITLE
Automatic cache regeneration upon cache clear

### ISSUE THREAD

**Issue by dimavisser** [Dropinbase/Releases#31]
Can DIB please connect the Clear all Cache & Crud button (red button) to automatic cache&crud generation? 

It happens a lot that, when working with one container, this button needs to be used to remove all code, elements and templates (since clearing only one container's cache & crud is very limited). Because of this, the whole system is wiped and when one needs to go look at another screen once in a while, it takes a very long time to load that.

![image](https://user-images.githubusercontent.com/33894592/89381206-14a85b80-d6f9-11ea-891f-f32796515482.png)

**Comment by cobuscoetsee** [comment]
Loading speed improved not an issue anymore.
