### ISSUE TITLE
Copy Paste JSON IN Tree

### ISSUE THREAD

**Issue by cobuscoetsee** [Dropinbase/Releases#33]
The ability to copy items into JSON and then to paste into the tree.  This will allow us to copy and paste items across environments and across projects.

**Comment by dawie-git** [comment]
Hi ... this is one of the first items I'd like to give attention to! There
is a real need. Also want to think about making this code useful for other
purposes like importing whole containers/dropins and Migrations.

**Comment by cobuscoetsee** [comment]
Done.
