### ISSUE TITLE
Cache the item tree client-side

### ISSUE THREAD

**Issue by dimavisser** [Dropinbase/Releases#9]
Cache the item tree client-side so it need not reload for every single expand/collapse - it consumes a lot of time having to sit and wait for the tree to load from the server every time you need to work with something. Container groups are especially slow.

You can create an async cache update call which is triggered **after** the tree expands - and decouple it from user client-side please, it will improve the experience dramatically.

![image](https://user-images.githubusercontent.com/33894592/84260954-359a6900-ab1b-11ea-9db8-7756d77f5762.png)

**Comment by cobuscoetsee** [comment]
Item tree was redone, resolved.
